import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="w-full h-[100vh] flex items-center justify-center">
            <Link href="/courses/new">
                <div className="h-3/6 w-2/6 rounded bg-gray-100 mr-3 flex justify-center items-center cursor-pointer">
                    <h1 className="text-4xl font-bold">Crea nuovo corso</h1>
                </div>
            </Link>
            <div className="h-3/6 w-2/6 rounded bg-gray-100">

            </div>
        </main>
    </>
  );
};

export default Home;

